import { getColorThemePreview } from './colorThemePreview'
import type { ResolvedColorTheme } from './colorThemeTypes'

function pickThemeColor(theme: ResolvedColorTheme, ids: readonly string[], fallback: string): string {
  for (const id of ids) {
    const value = theme.colors[id]
    if (typeof value === 'string' && value.trim().length > 0) {
      return value.trim()
    }
  }

  return fallback
}

export function getAppliedColorThemeVariables(theme: ResolvedColorTheme): Record<string, string> {
  const preview = getColorThemePreview(theme)
  const foreground = pickThemeColor(theme, ['foreground', 'editor.foreground'], preview.foreground)
  const border = pickThemeColor(theme, ['panel.border', 'sideBar.border', 'input.border'], `${preview.comment}55`)
  const accent = pickThemeColor(theme, ['button.background', 'focusBorder', 'list.highlightForeground'], preview.cyan)

  return {
    '--background': pickThemeColor(theme, ['editor.background', 'panel.background'], preview.background),
    '--foreground': foreground,
    '--card': pickThemeColor(theme, ['panel.background', 'editorWidget.background'], preview.surface),
    '--card-foreground': foreground,
    '--popover': pickThemeColor(theme, ['quickInput.background', 'editorWidget.background', 'menu.background'], preview.surface),
    '--popover-foreground': foreground,
    '--primary': accent,
    '--primary-foreground': pickThemeColor(theme, ['button.foreground', 'badge.foreground'], theme.kind === 'dark' ? '#ffffff' : '#ffffff'),
    '--secondary': pickThemeColor(theme, ['sideBar.background', 'panel.background', 'input.background'], preview.surface),
    '--secondary-foreground': foreground,
    '--muted': pickThemeColor(theme, ['list.inactiveSelectionBackground', 'sideBar.background', 'panel.background'], preview.surface),
    '--muted-foreground': pickThemeColor(theme, ['descriptionForeground', 'editorLineNumber.foreground', 'disabledForeground'], preview.comment),
    '--accent': pickThemeColor(theme, ['list.hoverBackground', 'toolbar.hoverBackground', 'button.secondaryHoverBackground'], preview.selection),
    '--accent-foreground': foreground,
    '--destructive': pickThemeColor(theme, ['errorForeground', 'editorError.foreground'], preview.red),
    '--destructive-foreground': theme.kind === 'dark' ? '#ffffff' : '#ffffff',
    '--border': border,
    '--input': border,
    '--input-background': pickThemeColor(theme, ['input.background', 'quickInput.background'], preview.input),
    '--switch-background': pickThemeColor(theme, ['checkbox.background', 'input.background'], preview.surface),
    '--ring': pickThemeColor(theme, ['focusBorder', 'button.background'], accent),
    '--sidebar': pickThemeColor(theme, ['sideBar.background'], preview.surface),
    '--sidebar-foreground': pickThemeColor(theme, ['sideBar.foreground', 'foreground'], foreground),
    '--sidebar-primary': pickThemeColor(theme, ['activityBar.background', 'button.background'], preview.surface),
    '--sidebar-primary-foreground': pickThemeColor(theme, ['activityBar.foreground', 'foreground'], foreground),
    '--sidebar-accent': pickThemeColor(theme, ['list.activeSelectionBackground', 'list.hoverBackground'], preview.selection),
    '--sidebar-accent-foreground': pickThemeColor(theme, ['foreground', 'sideBar.foreground'], foreground),
    '--sidebar-border': pickThemeColor(theme, ['sideBar.border', 'panel.border'], border),
    '--sidebar-ring': pickThemeColor(theme, ['focusBorder', 'button.background'], accent),

    '--ide-bg': pickThemeColor(theme, ['panel.background', 'editorGroupHeader.tabsBackground', 'editor.background'], preview.surface),
    '--ide-sidebar-bg': pickThemeColor(theme, ['sideBar.background'], preview.surface),
    '--ide-activitybar-bg': pickThemeColor(theme, ['activityBar.background'], preview.surface),
    '--ide-menubar-bg': pickThemeColor(theme, ['titleBar.activeBackground', 'menu.background'], preview.surface),
    '--ide-tab-bg': pickThemeColor(theme, ['tab.inactiveBackground', 'editorGroupHeader.tabsBackground'], preview.surface),
    '--ide-selection': pickThemeColor(theme, ['list.activeSelectionBackground', 'editor.selectionBackground'], preview.selection),
    '--ide-hover': pickThemeColor(theme, ['list.hoverBackground', 'toolbar.hoverBackground'], preview.selection),
    '--ide-tab-hover': pickThemeColor(theme, ['tab.hoverBackground', 'tab.activeBackground'], preview.surface),
    '--ide-editor-bg': pickThemeColor(theme, ['editor.background'], preview.background),
    '--ide-terminal-bg': pickThemeColor(theme, ['terminal.background', 'editor.background', 'panel.background'], preview.background),
    '--ide-text': foreground,
    '--ide-text-muted': pickThemeColor(theme, ['descriptionForeground', 'editorLineNumber.foreground'], preview.comment),
    '--ide-text-muted-stronger': pickThemeColor(theme, ['sideBarTitle.foreground', 'titleBar.activeForeground', 'statusBar.foreground'], preview.foreground),
    '--ide-text-section': pickThemeColor(theme, ['sideBarSectionHeader.foreground', 'sideBarTitle.foreground'], preview.foreground),
    '--ide-text-chevron': pickThemeColor(theme, ['icon.foreground', 'breadcrumb.foreground'], preview.comment),
    '--ide-text-dim': pickThemeColor(theme, ['disabledForeground'], preview.comment),
    '--ide-text-dimmer': pickThemeColor(theme, ['input.placeholderForeground', 'disabledForeground'], preview.comment),
    '--ide-border': border,
    '--ide-border-light': pickThemeColor(theme, ['input.border', 'widget.border', 'menu.border'], border),
    '--ide-btn-hover': pickThemeColor(theme, ['button.hoverBackground', 'toolbar.hoverBackground'], preview.selection),
    '--ide-accent': accent,
    '--ide-accent-dark': pickThemeColor(theme, ['button.hoverBackground', 'statusBar.debuggingBackground'], accent),
    '--ide-accent-vivid': pickThemeColor(theme, ['focusBorder', 'button.background'], accent),
    '--ide-accent-hover': pickThemeColor(theme, ['button.hoverBackground', 'statusBarItem.hoverBackground'], accent),
    '--ide-status-hover': pickThemeColor(theme, ['statusBarItem.hoverBackground', 'toolbar.hoverBackground'], preview.selection),
    '--ide-error': pickThemeColor(theme, ['errorForeground', 'editorError.foreground'], preview.red),
    '--ide-warning': pickThemeColor(theme, ['list.warningForeground', 'notificationsWarningIcon.foreground', 'editorWarning.foreground'], preview.orange),
    '--ide-info': pickThemeColor(theme, ['textLink.foreground', 'list.highlightForeground', 'editorLink.activeForeground'], preview.cyan),
    '--ide-info-bright': pickThemeColor(theme, ['editorLink.activeForeground', 'textLink.activeForeground'], preview.cyan),
    '--ide-success': pickThemeColor(theme, ['editorGutter.addedBackground', 'gitDecoration.addedResourceForeground'], preview.green),
    '--ide-file-v': preview.cyan,
    '--ide-file-sv': preview.pink,
    '--ide-file-hdl-header': preview.cyan,
    '--ide-file-software': preview.green,
    '--ide-file-python': preview.green,
    '--ide-file-xdc': preview.orange,
    '--ide-file-build': preview.purple,
    '--ide-file-asm': preview.orange,
    '--ide-file-linker': preview.yellow,
    '--ide-file-filelist': preview.cyan,
    '--ide-file-config': preview.cyan,
    '--ide-file-script': preview.green,
    '--ide-file-git': preview.red,
    '--ide-file-license': preview.yellow,
    '--ide-file-shell': preview.green,
    '--ide-file-yaml': preview.orange,
    '--ide-file-md': preview.cyan,
    '--ide-syntax-keyword': preview.pink,
    '--ide-syntax-function': preview.purple,
    '--ide-syntax-number': preview.green,
    '--ide-syntax-string': preview.yellow,
    '--ide-syntax-folder': preview.orange,
    '--ide-cursor': pickThemeColor(theme, ['editorCursor.foreground', 'terminalCursor.foreground'], preview.brightForeground),
    '--ide-pro': preview.yellow,
    '--ide-online': preview.green,
    '--ide-close': preview.red,
    '--ide-dracula-surface': preview.surface,
    '--ide-dracula-background': preview.background,
    '--ide-dracula-input': preview.input,
    '--ide-dracula-selection': preview.selection,
    '--ide-dracula-comment': preview.comment,
    '--ide-dracula-foreground': preview.foreground,
    '--ide-dracula-bright-foreground': preview.brightForeground,
    '--ide-dracula-pink': preview.pink,
    '--ide-dracula-purple': preview.purple,
    '--ide-dracula-cyan': preview.cyan,
    '--ide-dracula-green': preview.green,
    '--ide-dracula-yellow': preview.yellow,
    '--ide-dracula-red': preview.red,
    '--ide-dracula-orange': preview.orange,
    '--ide-chat-bg': pickThemeColor(theme, ['panel.background', 'sideBar.background'], preview.surface),
    '--ide-chat-dropdown': pickThemeColor(theme, ['editorWidget.background', 'quickInput.background'], preview.surface),
    '--ide-chat-hover': pickThemeColor(theme, ['list.hoverBackground', 'toolbar.hoverBackground'], preview.selection),
    '--ide-chat-input': pickThemeColor(theme, ['input.background', 'quickInput.background'], preview.input),
    '--ide-chat-border': pickThemeColor(theme, ['input.border', 'widget.border'], border),
    '--ide-chat-muted': pickThemeColor(theme, ['descriptionForeground', 'disabledForeground'], preview.comment),
    '--ide-chat-text': foreground,
    '--ide-chat-purple': preview.purple,
    '--ide-chat-purple-hover': preview.pink,
    '--ide-chat-cyan': preview.cyan,
    '--ide-chat-text-bright': preview.brightForeground,
    '--ide-chat-input-border': pickThemeColor(theme, ['input.border', 'widget.border'], border),
  }
}
