export const ASSISTANT_THREAD_LIST_MIN_WIDTH_PX = 140;
export const ASSISTANT_THREAD_LIST_DEFAULT_WIDTH_PX = ASSISTANT_THREAD_LIST_MIN_WIDTH_PX;
export const ASSISTANT_THREAD_LIST_MAX_WIDTH_PX = 420;
export const ASSISTANT_THREAD_LIST_RESIZE_HANDLE_WIDTH_PX = 8;