import type { DraculaPalette } from './themeSource'

export type MonacoBaseTheme = 'vs' | 'vs-dark'

type EditorThemeCatalogMetadata = {
  value: string
  label: string
  description: string
  author: string
  sourceUrl: string
  license: string
}

type DynamicEditorThemeCatalogEntry = EditorThemeCatalogMetadata & {
  kind: 'dynamic'
  base: MonacoBaseTheme
}

type StaticEditorThemeCatalogDefinition = EditorThemeCatalogMetadata & {
  kind: 'static'
  base: MonacoBaseTheme
  palette: DraculaPalette
}

export type EditorThemeCatalogEntry = DynamicEditorThemeCatalogEntry | StaticEditorThemeCatalogDefinition

export const editorThemeCatalog = [
  {
    kind: 'dynamic',
    value: 'dracula',
    label: 'Dracula',
    description: 'Default dark theme with vivid accents.',
    author: 'Dracula Theme',
    sourceUrl: 'https://github.com/dracula/visual-studio-code',
    license: 'MIT',
    base: 'vs-dark',
  },
  {
    kind: 'static',
    value: 'github-light',
    label: 'GitHub Light',
    description: 'Clean light theme inspired by GitHub.',
    author: 'GitHub',
    sourceUrl: 'https://github.com/primer/github-vscode-theme',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#f6f8fa',
      background: '#ffffff',
      input: '#ffffff',
      selection: '#dbe9ff',
      comment: '#6e7781',
      foreground: '#1f2328',
      brightForeground: '#24292f',
      pink: '#cf222e',
      purple: '#8250df',
      cyan: '#0550ae',
      green: '#116329',
      yellow: '#9a6700',
      red: '#cf222e',
      orange: '#bc4c00',
    },
  },
  {
    kind: 'static',
    value: 'github-dark',
    label: 'GitHub Dark',
    description: 'GitHub-style dark theme with neutral contrast.',
    author: 'GitHub',
    sourceUrl: 'https://github.com/primer/github-vscode-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#161b22',
      background: '#0d1117',
      input: '#21262d',
      selection: '#264f78',
      comment: '#8b949e',
      foreground: '#c9d1d9',
      brightForeground: '#f0f6fc',
      pink: '#ff7b72',
      purple: '#d2a8ff',
      cyan: '#79c0ff',
      green: '#7ee787',
      yellow: '#d29922',
      red: '#ff7b72',
      orange: '#ffa657',
    },
  },
  {
    kind: 'static',
    value: 'one-dark-pro',
    label: 'One Dark Pro',
    description: 'Balanced dark theme with familiar VS Code tones.',
    author: 'Binaryify',
    sourceUrl: 'https://github.com/Binaryify/OneDark-Pro',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#21252b',
      background: '#282c34',
      input: '#2c313c',
      selection: '#3e4451',
      comment: '#5c6370',
      foreground: '#abb2bf',
      brightForeground: '#d7dae0',
      pink: '#c678dd',
      purple: '#c678dd',
      cyan: '#56b6c2',
      green: '#98c379',
      yellow: '#e5c07b',
      red: '#e06c75',
      orange: '#d19a66',
    },
  },
  {
    kind: 'static',
    value: 'night-owl',
    label: 'Night Owl',
    description: 'High-contrast dark palette for long coding sessions.',
    author: 'Sarah Drasner',
    sourceUrl: 'https://github.com/sdras/night-owl-vscode-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#102131',
      background: '#011627',
      input: '#122d42',
      selection: '#1d3b53',
      comment: '#637777',
      foreground: '#d6deeb',
      brightForeground: '#ffffff',
      pink: '#c792ea',
      purple: '#c792ea',
      cyan: '#82aaff',
      green: '#addb67',
      yellow: '#ecc48d',
      red: '#ef5350',
      orange: '#f78c6c',
    },
  },
  {
    kind: 'static',
    value: 'tokyo-night',
    label: 'Tokyo Night',
    description: 'Modern deep-blue theme with cool accents.',
    author: 'enkia',
    sourceUrl: 'https://github.com/tokyo-night/tokyo-night-vscode-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#1f2335',
      background: '#1a1b26',
      input: '#24283b',
      selection: '#33467c',
      comment: '#565f89',
      foreground: '#c0caf5',
      brightForeground: '#d5d6db',
      pink: '#ff79c6',
      purple: '#bb9af7',
      cyan: '#7dcfff',
      green: '#9ece6a',
      yellow: '#e0af68',
      red: '#f7768e',
      orange: '#ff9e64',
    },
  },
  {
    kind: 'static',
    value: 'solarized-light',
    label: 'Solarized Light',
    description: 'Soft light theme with reduced glare.',
    author: 'Ethan Schoonover',
    sourceUrl: 'https://github.com/altercation/solarized',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#eee8d5',
      background: '#fdf6e3',
      input: '#fdf6e3',
      selection: '#eee8d5',
      comment: '#93a1a1',
      foreground: '#657b83',
      brightForeground: '#586e75',
      pink: '#d33682',
      purple: '#6c71c4',
      cyan: '#2aa198',
      green: '#859900',
      yellow: '#b58900',
      red: '#dc322f',
      orange: '#cb4b16',
    },
  },
  {
    kind: 'static',
    value: 'solarized-dark',
    label: 'Solarized Dark',
    description: 'Muted dark theme based on Solarized.',
    author: 'Ethan Schoonover',
    sourceUrl: 'https://github.com/altercation/solarized',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#073642',
      background: '#002b36',
      input: '#073642',
      selection: '#134b5c',
      comment: '#586e75',
      foreground: '#839496',
      brightForeground: '#93a1a1',
      pink: '#d33682',
      purple: '#6c71c4',
      cyan: '#2aa198',
      green: '#859900',
      yellow: '#b58900',
      red: '#dc322f',
      orange: '#cb4b16',
    },
  },
  {
    kind: 'static',
    value: 'atom-one-dark',
    label: 'Atom One Dark',
    description: 'Atom-inspired dark theme with crisp blue and magenta accents.',
    author: 'akamud',
    sourceUrl: 'https://github.com/akamud/vscode-theme-onedark',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#333842',
      background: '#282C34',
      input: '#2C313A',
      selection: '#3E4451',
      comment: '#5C6370',
      foreground: '#ABB2BF',
      brightForeground: '#D7DAE0',
      pink: '#C678DD',
      purple: '#C678DD',
      cyan: '#56B6C2',
      green: '#98C379',
      yellow: '#E5C07B',
      red: '#E06C75',
      orange: '#D19A66',
    },
  },
  {
    kind: 'static',
    value: 'catppuccin-mocha',
    label: 'Catppuccin Mocha',
    description: 'Warm dark pastel theme with soft contrast and cozy accents.',
    author: 'Catppuccin Organization',
    sourceUrl: 'https://github.com/catppuccin/vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#313244',
      background: '#1e1e2e',
      input: '#45475a',
      selection: '#45475a',
      comment: '#585b70',
      foreground: '#cdd6f4',
      brightForeground: '#f5f5f5',
      pink: '#f5c2e7',
      purple: '#cba6f7',
      cyan: '#89dceb',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      red: '#f38ba8',
      orange: '#fab387',
    },
  },
  {
    kind: 'static',
    value: 'catppuccin-latte',
    label: 'Catppuccin Latte',
    description: 'Creamy light pastel theme with balanced color pops.',
    author: 'Catppuccin Organization',
    sourceUrl: 'https://github.com/catppuccin/vscode',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#ccd0da',
      background: '#eff1f5',
      input: '#e6e9ef',
      selection: '#bcc0cc',
      comment: '#9ca0b0',
      foreground: '#4c4f69',
      brightForeground: '#1e1e2e',
      pink: '#ea76cb',
      purple: '#8839ef',
      cyan: '#04a5e5',
      green: '#40a02b',
      yellow: '#df8e1d',
      red: '#d20f39',
      orange: '#fe640b',
    },
  },
  {
    kind: 'static',
    value: 'nord',
    label: 'Nord',
    description: 'Clean arctic dark theme with restrained cool tones.',
    author: 'Sven Greb',
    sourceUrl: 'https://github.com/nordtheme/vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#3b4252',
      background: '#2e3440',
      input: '#434c5e',
      selection: '#434c5e',
      comment: '#616e88',
      foreground: '#d8dee9',
      brightForeground: '#eceff4',
      pink: '#b48ead',
      purple: '#b48ead',
      cyan: '#88c0d0',
      green: '#a3be8c',
      yellow: '#ebcb8b',
      red: '#bf616a',
      orange: '#d08770',
    },
  },
  {
    kind: 'static',
    value: 'rose-pine',
    label: 'Rose Pine',
    description: 'Soft moody dark theme built around muted mauves and gold.',
    author: 'Rose Pine',
    sourceUrl: 'https://github.com/rose-pine/vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#26233a',
      background: '#191724',
      input: '#1f1d2e',
      selection: '#403d52',
      comment: '#6e6a86',
      foreground: '#e0def4',
      brightForeground: '#f5f5f5',
      pink: '#ebbcba',
      purple: '#c4a7e7',
      cyan: '#9ccfd8',
      green: '#31748f',
      yellow: '#f6c177',
      red: '#eb6f92',
      orange: '#ebbcba',
    },
  },
  {
    kind: 'static',
    value: 'rose-pine-dawn',
    label: 'Rose Pine Dawn',
    description: 'Airy light variant of Rose Pine with dusty pastel warmth.',
    author: 'Rose Pine',
    sourceUrl: 'https://github.com/rose-pine/vscode',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#f2e9e1',
      background: '#faf4ed',
      input: '#fffaf3',
      selection: '#dfdad9',
      comment: '#9893a5',
      foreground: '#575279',
      brightForeground: '#1e1e2e',
      pink: '#d7827e',
      purple: '#907aa9',
      cyan: '#56949f',
      green: '#286983',
      yellow: '#ea9d34',
      red: '#b4637a',
      orange: '#d7827e',
    },
  },
  {
    kind: 'static',
    value: 'min-dark',
    label: 'Min Dark',
    description: 'Minimal dark theme with desaturated chrome and sharp accents.',
    author: 'Miguel Solorio',
    sourceUrl: 'https://github.com/miguelsolorio/min-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#1A1A1A',
      background: '#1f1f1f',
      input: '#2A2A2A',
      selection: '#383838',
      comment: '#6b737c',
      foreground: '#E0E0E0',
      brightForeground: '#FAFAFA',
      pink: '#FF7A84',
      purple: '#b392f0',
      cyan: '#79b8ff',
      green: '#9db1c5',
      yellow: '#FF9800',
      red: '#f97583',
      orange: '#ffab70',
    },
  },
  {
    kind: 'static',
    value: 'min-light',
    label: 'Min Light',
    description: 'Minimal light theme with restrained neutrals and quiet contrast.',
    author: 'Miguel Solorio',
    sourceUrl: 'https://github.com/miguelsolorio/min-theme',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#f6f6f6',
      background: '#ffffff',
      input: '#F3F3F3',
      selection: '#E7F3FF',
      comment: '#c2c3c5',
      foreground: '#212121',
      brightForeground: '#24292e',
      pink: '#6f42c1',
      purple: '#6f42c1',
      cyan: '#1976D2',
      green: '#22863a',
      yellow: '#FF9800',
      red: '#D32F2F',
      orange: '#dd8500',
    },
  },
  {
    kind: 'static',
    value: 'gruvbox-dark-hard',
    label: 'Gruvbox Dark Hard',
    description: 'High-contrast Gruvbox variant with rich earthy dark tones.',
    author: 'jdinhify',
    sourceUrl: 'https://github.com/jdinhify/vscode-theme-gruvbox',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#3c3836',
      background: '#1d2021',
      input: '#1d2021',
      selection: '#34413a',
      comment: '#928374',
      foreground: '#ebdbb2',
      brightForeground: '#fbf1c7',
      pink: '#b16286',
      purple: '#d3869b',
      cyan: '#8ec07c',
      green: '#b8bb26',
      yellow: '#fabd2f',
      red: '#fb4934',
      orange: '#fe8019',
    },
  },
  {
    kind: 'static',
    value: 'gruvbox-light-hard',
    label: 'Gruvbox Light Hard',
    description: 'Bright Gruvbox light variant with warm retro contrast.',
    author: 'jdinhify',
    sourceUrl: 'https://github.com/jdinhify/vscode-theme-gruvbox',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#ebdbb2',
      background: '#f9f5d7',
      input: '#f9f5d7',
      selection: '#d7cfb2',
      comment: '#928374',
      foreground: '#3c3836',
      brightForeground: '#282828',
      pink: '#8f3f71',
      purple: '#8f3f71',
      cyan: '#427b58',
      green: '#79740e',
      yellow: '#b57614',
      red: '#9d0006',
      orange: '#af3a03',
    },
  },
  {
    kind: 'static',
    value: 'ayu-mirage',
    label: 'Ayu Mirage',
    description: 'Low-glare dark theme with warm highlights and cool blues.',
    author: 'teabyii',
    sourceUrl: 'https://github.com/ayu-theme/vscode-ayu',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#242936',
      background: '#1f2430',
      input: '#2d3343',
      selection: '#33415e',
      comment: '#5c6773',
      foreground: '#cbccc6',
      brightForeground: '#ffffff',
      pink: '#f29e74',
      purple: '#d4bfff',
      cyan: '#5ccfe6',
      green: '#bae67e',
      yellow: '#ffd580',
      red: '#f28779',
      orange: '#ffad66',
    },
  },
  {
    kind: 'static',
    value: 'ayu-light',
    label: 'Ayu Light',
    description: 'Warm light theme with soft neutrals and restrained saturation.',
    author: 'teabyii',
    sourceUrl: 'https://github.com/ayu-theme/vscode-ayu',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#f3f4f5',
      background: '#fafafa',
      input: '#ffffff',
      selection: '#dde7f0',
      comment: '#abb0b6',
      foreground: '#5c6166',
      brightForeground: '#000000',
      pink: '#f07171',
      purple: '#a37acc',
      cyan: '#55b4d4',
      green: '#86b300',
      yellow: '#f2ae49',
      red: '#f07171',
      orange: '#fa8d3e',
    },
  },
  {
    kind: 'static',
    value: 'noctis',
    label: 'Noctis',
    description: 'Dense dark theme with cool blues and bright magenta accents.',
    author: 'Liviu Schera',
    sourceUrl: 'https://github.com/liviuschera/noctis',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#1a252f',
      background: '#011627',
      input: '#1d3b53',
      selection: '#0f2d42',
      comment: '#637684',
      foreground: '#d6deeb',
      brightForeground: '#ffffff',
      pink: '#ff5874',
      purple: '#c792ea',
      cyan: '#82aaff',
      green: '#7fd56d',
      yellow: '#ffd000',
      red: '#ff6b6b',
      orange: '#ffaa44',
    },
  },
  {
    kind: 'static',
    value: 'noctis-lux',
    label: 'Noctis Lux',
    description: 'Bright light variant of Noctis with vivid editorial accents.',
    author: 'Liviu Schera',
    sourceUrl: 'https://github.com/liviuschera/noctis',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#f2edde',
      background: '#fef8ec',
      input: '#fef8ec',
      selection: '#ade2eb',
      comment: '#8ca6a6',
      foreground: '#005661',
      brightForeground: '#000000',
      pink: '#ff5792',
      purple: '#9075d8',
      cyan: '#00c6e0',
      green: '#8ce99a',
      yellow: '#f49725',
      red: '#ff4000',
      orange: '#e9a149',
    },
  },
  {
    kind: 'static',
    value: 'moonlight-ii',
    label: 'Moonlight II',
    description: 'Luminous dark theme with saturated blues and neon pastels.',
    author: 'atomiks',
    sourceUrl: 'https://github.com/atomiks/moonlight-vscode-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#1e2030',
      background: '#222436',
      input: '#191a2a',
      selection: '#2f334d',
      comment: '#7a88cf',
      foreground: '#c8d3f5',
      brightForeground: '#d5def8',
      pink: '#fca7ea',
      purple: '#c4a2ff',
      cyan: '#78dbff',
      green: '#c3e88d',
      yellow: '#ffc777',
      red: '#ff757f',
      orange: '#ff966c',
    },
  },
  {
    kind: 'static',
    value: 'alabaster',
    label: 'Alabaster',
    description: 'Minimal light theme that highlights only the essentials.',
    author: 'Nikita Prokopov',
    sourceUrl: 'https://github.com/tonsky/vscode-theme-alabaster',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#F0F0F0',
      background: '#F7F7F7',
      input: '#FFFFFF',
      selection: '#BFDBFE',
      comment: '#AA3731',
      foreground: '#000000',
      brightForeground: '#434343',
      pink: '#E64CE6',
      purple: '#7A3E9D',
      cyan: '#0083B2',
      green: '#448C27',
      yellow: '#CB9000',
      red: '#AA3731',
      orange: '#FFBC5D',
    },
  },
  {
    kind: 'static',
    value: 'synthwave-84',
    label: "Synthwave '84",
    description: 'Retro 80s-inspired dark theme with neon synthwave accents.',
    author: 'Robb Owen',
    sourceUrl: 'https://github.com/robb0wen/synthwave-vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#2A2139',
      background: '#2A2139',
      input: '#1A0E1F',
      selection: '#34294F',
      comment: '#6D77B3',
      foreground: '#F4EEE4',
      brightForeground: '#FDFDFD',
      pink: '#F92AAD',
      purple: '#988BC7',
      cyan: '#03EDF9',
      green: '#72F1B8',
      yellow: '#FEDE5D',
      red: '#FF7EDB',
      orange: '#F39F05',
    },
  },
  {
    kind: 'static',
    value: 'andromeda',
    label: 'Andromeda',
    description: 'Spacey dark theme with cyan, coral, and violet contrast.',
    author: 'Eliver Lara',
    sourceUrl: 'https://github.com/EliverLara/Andromeda',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#0F111B',
      background: '#0F111B',
      input: '#0F111B',
      selection: '#1A1D2B',
      comment: '#384854',
      foreground: '#CFD9DB',
      brightForeground: '#FFFFFF',
      pink: '#FF6B6B',
      purple: '#C792EA',
      cyan: '#00D4FF',
      green: '#7EC699',
      yellow: '#FFB86C',
      red: '#FF6B6B',
      orange: '#FFA500',
    },
  },
  {
    kind: 'static',
    value: 'bluloco-dark',
    label: 'Bluloco Dark',
    description: 'Blue-forward dark theme with balanced warm accent colors.',
    author: 'uloco',
    sourceUrl: 'https://github.com/uloco/theme-bluloco-dark',
    license: 'LGPL-3.0',
    base: 'vs-dark',
    palette: {
      surface: '#282C34',
      background: '#282C34',
      input: '#1E2127',
      selection: '#3E4451',
      comment: '#636D83',
      foreground: '#ABB2BF',
      brightForeground: '#FFFFFF',
      pink: '#FF6480',
      purple: '#9F7EFE',
      cyan: '#56B6C2',
      green: '#3FC56B',
      yellow: '#E5C07B',
      red: '#E06C75',
      orange: '#FF936A',
    },
  },
  {
    kind: 'static',
    value: 'bluloco-light',
    label: 'Bluloco Light',
    description: 'Bright light variant with cool blues and restrained warm accents.',
    author: 'uloco',
    sourceUrl: 'https://github.com/uloco/theme-bluloco-light',
    license: 'LGPL-3.0',
    base: 'vs',
    palette: {
      surface: '#F9F9F9',
      background: '#F9F9F9',
      input: '#FAFAFA',
      selection: '#E5E5E6',
      comment: '#A0A1A7',
      foreground: '#383A42',
      brightForeground: '#000000',
      pink: '#D52753',
      purple: '#823FF1',
      cyan: '#275FE4',
      green: '#23974A',
      yellow: '#C5A332',
      red: '#CA1243',
      orange: '#DF631C',
    },
  },
  {
    kind: 'static',
    value: 'cobalt2',
    label: 'Cobalt2',
    description: 'Saturated blue theme inspired by the classic Cobalt editor palette.',
    author: 'Wes Bos, Roberto Achar',
    sourceUrl: 'https://github.com/wesbos/cobalt2-vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#122738',
      background: '#1D3A52',
      input: '#0F1F2E',
      selection: '#1F4662',
      comment: '#3F5D7F',
      foreground: '#CED1CF',
      brightForeground: '#FFFFFF',
      pink: '#FF628C',
      purple: '#9EFFFF',
      cyan: '#00DAFF',
      green: '#3AD900',
      yellow: '#FFC600',
      red: '#FF0088',
      orange: '#FF9D00',
    },
  },
  {
    kind: 'static',
    value: 'omni',
    label: 'Omni',
    description: 'Elegant dark theme with purple-pink highlights and cool cyan accents.',
    author: 'Rocketseat (Joao Pedro Schmitz)',
    sourceUrl: 'https://github.com/getomni/visual-studio-code',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#191622',
      background: '#191622',
      input: '#0D0310',
      selection: '#41414D',
      comment: '#483C67',
      foreground: '#E1E1E6',
      brightForeground: '#FFFFFF',
      pink: '#FF79C6',
      purple: '#988BC7',
      cyan: '#78D1E1',
      green: '#67E480',
      yellow: '#E7DE79',
      red: '#E96379',
      orange: '#E89E64',
    },
  },
  {
    kind: 'static',
    value: 'horizon',
    label: 'Horizon',
    description: 'Warm retro dark theme with sunset pinks, golds, and seafoam accents.',
    author: 'Jonathan Olaleye',
    sourceUrl: 'https://github.com/jolaleye/horizon-theme-vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#1C1E26',
      background: '#1C1E26',
      input: '#0F1119',
      selection: '#203248',
      comment: '#5B858D',
      foreground: '#C7C9CB',
      brightForeground: '#FFFFFF',
      pink: '#F7B3A1',
      purple: '#B39DF3',
      cyan: '#5DE4C7',
      green: '#09F7A0',
      yellow: '#FAD430',
      red: '#EC6A88',
      orange: '#F09383',
    },
  },
  {
    kind: 'static',
    value: 'horizon-bright',
    label: 'Horizon Bright',
    description: 'Warm light variant of Horizon with gentle paper tones and sunset accents.',
    author: 'Jonathan Olaleye',
    sourceUrl: 'https://github.com/jolaleye/horizon-theme-vscode',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#FAF5F1',
      background: '#FAF5F1',
      input: '#F5F1ED',
      selection: '#E0D9CE',
      comment: '#958B7F',
      foreground: '#403F53',
      brightForeground: '#000000',
      pink: '#D8137F',
      purple: '#8B63D8',
      cyan: '#097C6D',
      green: '#1B9968',
      yellow: '#B65D07',
      red: '#D8137F',
      orange: '#C95734',
    },
  },
  {
    kind: 'static',
    value: 'shades-of-purple',
    label: 'Shades of Purple',
    description: 'High-contrast purple theme tuned for readability and vivid syntax colors.',
    author: 'Ahmad Awais',
    sourceUrl: 'https://github.com/ahmadawais/shades-of-purple-vscode',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#2D2B55',
      background: '#2D2B55',
      input: '#1A1832',
      selection: '#453C67',
      comment: '#B362FF',
      foreground: '#A599E9',
      brightForeground: '#FFFFFF',
      pink: '#FF628C',
      purple: '#6679CC',
      cyan: '#9EFFFF',
      green: '#A5FF90',
      yellow: '#FFDC5D',
      red: '#FF0000',
      orange: '#FF9D00',
    },
  },
  {
    kind: 'static',
    value: 'winter-is-coming-dark-blue',
    label: 'Winter is Coming (Dark Blue)',
    description: 'Cool blue flagship variant of Winter is Coming with icy contrast.',
    author: 'John Papa',
    sourceUrl: 'https://github.com/johnpapa/vscode-winteriscoming',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#0B2942',
      background: '#011627',
      input: '#0B253A',
      selection: '#103362',
      comment: '#999999',
      foreground: '#A7DBF7',
      brightForeground: '#D6DEEB',
      pink: '#D29FFC',
      purple: '#C792EA',
      cyan: '#57CDFF',
      green: '#78BD65',
      yellow: '#F7ECB5',
      red: '#EF5350',
      orange: '#FFCA28',
    },
  },
  {
    kind: 'static',
    value: 'winter-is-coming-dark',
    label: 'Winter is Coming (Dark)',
    description: 'Neutral charcoal variant of Winter is Coming with icy syntax accents.',
    author: 'John Papa',
    sourceUrl: 'https://github.com/johnpapa/vscode-winteriscoming',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#0B2942',
      background: '#282822',
      input: '#0B253A',
      selection: '#103362',
      comment: '#999999',
      foreground: '#A7DBF7',
      brightForeground: '#D6DEEB',
      pink: '#D29FFC',
      purple: '#C792EA',
      cyan: '#57CDFF',
      green: '#78BD65',
      yellow: '#F7ECB5',
      red: '#EF5350',
      orange: '#FFCA28',
    },
  },
  {
    kind: 'static',
    value: 'winter-is-coming-light',
    label: 'Winter is Coming (Light)',
    description: 'Bright light variant of Winter is Coming tuned for daytime coding.',
    author: 'John Papa, Brian Clark',
    sourceUrl: 'https://github.com/johnpapa/vscode-winteriscoming',
    license: 'MIT',
    base: 'vs',
    palette: {
      surface: '#F3F3F3',
      background: '#FFFFFF',
      input: '#EEEEEE',
      selection: '#CEE1F0',
      comment: '#357B42',
      foreground: '#236EBF',
      brightForeground: '#1857A4',
      pink: '#A44185',
      purple: '#7C2CBD',
      cyan: '#2F86D2',
      green: '#296D31',
      yellow: '#DF8618',
      red: '#EF5350',
      orange: '#DA5221',
    },
  },
  {
    kind: 'static',
    value: 'monokai-night',
    label: 'Monokai Night',
    description: 'Minimal dark Monokai variant with restrained chrome and vivid syntax colors.',
    author: 'Fabio Spampinato',
    sourceUrl: 'https://github.com/fabiospampinato/vscode-monokai-night',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#161616',
      background: '#1F1F1F',
      input: '#363636',
      selection: '#464646',
      comment: '#75715E',
      foreground: '#DDDDDD',
      brightForeground: '#F8F8F2',
      pink: '#F92672',
      purple: '#AE81FF',
      cyan: '#66D9EF',
      green: '#A6E22E',
      yellow: '#E6DB74',
      red: '#C4265E',
      orange: '#FD971F',
    },
  },
  {
    kind: 'static',
    value: 'aura-dark',
    label: 'Aura Dark',
    description: 'Velvety dark theme with luminous violet, mint, and rose accents.',
    author: 'Dalton Menezes',
    sourceUrl: 'https://github.com/daltonmenezes/aura-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#110F18',
      background: '#15141B',
      input: '#15141B',
      selection: '#3D375E7F',
      comment: '#6D6D6D',
      foreground: '#EDECEE',
      brightForeground: '#CDCCCE',
      pink: '#F694FF',
      purple: '#A277FF',
      cyan: '#82E2FF',
      green: '#61FFCA',
      yellow: '#FFCA85',
      red: '#FF6767',
      orange: '#FFCA85',
    },
  },
  {
    kind: 'static',
    value: 'aura-soft-dark',
    label: 'Aura Soft Dark',
    description: 'Softer Aura variant with plush dark surfaces and glowing pastel accents.',
    author: 'Dalton Menezes',
    sourceUrl: 'https://github.com/daltonmenezes/aura-theme',
    license: 'MIT',
    base: 'vs-dark',
    palette: {
      surface: '#1C1B22',
      background: '#21202E',
      input: '#21202E',
      selection: '#3D375E7F',
      comment: '#6D6D6D',
      foreground: '#EDECEE',
      brightForeground: '#CDCCCE',
      pink: '#F694FF',
      purple: '#A277FF',
      cyan: '#82E2FF',
      green: '#61FFCA',
      yellow: '#FFCA85',
      red: '#FF6767',
      orange: '#FFCA85',
    },
  },
] as const satisfies readonly EditorThemeCatalogEntry[]

export type EditorThemeCatalogId = (typeof editorThemeCatalog)[number]['value']
export type StaticEditorThemeCatalogEntry = Extract<(typeof editorThemeCatalog)[number], { kind: 'static' }>

export const editorThemeCatalogById = new Map<EditorThemeCatalogId, (typeof editorThemeCatalog)[number]>(
  editorThemeCatalog.map((entry) => [entry.value, entry]),
)

export function isStaticEditorThemeCatalogEntry(
  entry: (typeof editorThemeCatalog)[number],
): entry is StaticEditorThemeCatalogEntry {
  return entry.kind === 'static'
}