// ─── IPC Channel Constants ────────────────────────────────────────────────────
// Three-tier classification per architecture constraints:
//   sync:   — synchronous queries (<10ms), lightweight reads only
//   async:  — asynchronous invoke/handle, non-blocking UI
//   stream: — main→renderer push, <50ms latency target

export const SyncChannels = {
  PLATFORM: 'sync:platform',
  CONFIG_GET: 'sync:config:get',
  WINDOW_IS_MAXIMIZED: 'sync:window:is-maximized',
  WINDOW_IS_FULLSCREEN: 'sync:window:is-full-screen',
} as const;

export const AsyncChannels = {
  PLATFORM_GET_GPU_DIAGNOSTICS: 'async:platform:get-gpu-diagnostics',
  AUTH_OPEN_ACCOUNT_PAGE: 'async:auth:open-account-page',
  AUTH_GET_SESSION: 'async:auth:get-session',
  AUTH_SIGN_OUT: 'async:auth:sign-out',
  AUTH_SYNC_CONFIG: 'async:auth:sync-config',
  NOTICES_REVEAL_BUNDLED_FILES: 'async:notices:reveal-bundled-files',
  NOTIFICATIONS_DISMISS: 'async:notifications:dismiss',
  NOTIFICATIONS_GET_HISTORY: 'async:notifications:get-history',
  NOTIFICATIONS_PUBLISH: 'async:notifications:publish',
  DIALOG_SHOW_SAVE: 'async:dialog:show-save',
  DIALOG_SHOW_OPEN_THEME: 'async:dialog:show-open-theme',
  DIALOG_SHOW_OPEN_PROJECT_DIRECTORY: 'async:dialog:show-open-project-directory',
  WINDOW_MINIMIZE: 'async:window:minimize',
  WINDOW_MAXIMIZE: 'async:window:maximize',
  WINDOW_SHOW: 'async:window:show',
  WINDOW_HIDE: 'async:window:hide',
  WINDOW_CLOSE: 'async:window:close',
  WINDOW_MARK_WORKSPACE_READY: 'async:window:mark-workspace-ready',
  WINDOW_RESOLVE_CLOSE_REQUEST: 'async:window:resolve-close-request',
  WINDOW_SET_FLOATING_INFO_VISIBILITY: 'async:window:set-floating-info-visibility',
  WINDOW_SET_FLOATING_INFO_EXPANDED: 'async:window:set-floating-info-expanded',
  WINDOW_SET_FLOATING_INFO_MODE: 'async:window:set-floating-info-mode',
  PROJECT_CREATE: 'async:project:create',
  PROJECT_OPEN: 'async:project:open',
  PROJECT_CLOSE: 'async:project:close',
  PROJECT_GET_CURRENT: 'async:project:get-current',
  PROJECT_FLUSH_SESSION: 'async:project:flush-session',
  PROJECT_UPDATE_CONFIG: 'async:project:update-config',
  FS_READ_FILE: 'async:fs:read-file',
  FS_READ_FILE_ABSOLUTE: 'async:fs:read-file-absolute',
  FS_LIST_FILES: 'async:fs:list-files',
  FS_WRITE_FILE: 'async:fs:write-file',
  FS_WRITE_FILE_ABSOLUTE: 'async:fs:write-file-absolute',
  FS_CREATE_DIRECTORY: 'async:fs:create-directory',
  FS_COPY_FILE: 'async:fs:copy-file',
  FS_COPY_DIRECTORY: 'async:fs:copy-directory',
  FS_DELETE_FILE: 'async:fs:delete-file',
  FS_DELETE_DIRECTORY: 'async:fs:delete-directory',
  FS_RENAME: 'async:fs:rename',
  FS_READ_DIR: 'async:fs:read-dir',
  FS_STAT: 'async:fs:stat',
  FS_EXISTS: 'async:fs:exists',
  GIT_GET_STATUS: 'async:git:get-status',
  GIT_GET_FILE_DIFF: 'async:git:get-file-diff',
  SHELL_EXEC: 'async:shell:exec',
  SHELL_KILL: 'async:shell:kill',
  TERMINAL_CREATE: 'async:terminal:create',
  TERMINAL_WRITE: 'async:terminal:write',
  TERMINAL_RESIZE: 'async:terminal:resize',
  TERMINAL_KILL: 'async:terminal:kill',
  WSL_START_PRISTINE_EDA_ENVIRONMENT: 'async:wsl:start-pristine-eda-environment',
  WSL_STOP_PRISTINE_EDA_ENVIRONMENT: 'async:wsl:stop-pristine-eda-environment',
  WSL_GET_PRISTINE_EDA_ENVIRONMENT_STATUS: 'async:wsl:get-pristine-eda-environment-status',
  LSP_ENSURE_INITIALIZED: 'async:lsp:ensure-initialized',
  LSP_OPEN_DOCUMENT: 'async:lsp:open-document',
  LSP_CHANGE_DOCUMENT: 'async:lsp:change-document',
  LSP_CLOSE_DOCUMENT: 'async:lsp:close-document',
  LSP_COMPLETION: 'async:lsp:completion',
  LSP_COMPLETION_RESOLVE: 'async:lsp:completion-resolve',
  LSP_HOVER: 'async:lsp:hover',
  LSP_DEFINITION: 'async:lsp:definition',
  LSP_TYPE_DEFINITION: 'async:lsp:type-definition',
  LSP_IMPLEMENTATION: 'async:lsp:implementation',
  LSP_DOCUMENT_HIGHLIGHTS: 'async:lsp:document-highlights',
  LSP_DOCUMENT_LINKS: 'async:lsp:document-links',
  LSP_INLAY_HINTS: 'async:lsp:inlay-hints',
  LSP_CODE_ACTIONS: 'async:lsp:code-actions',
  LSP_FOLDING_RANGES: 'async:lsp:folding-ranges',
  LSP_SEMANTIC_TOKENS_FULL: 'async:lsp:semantic-tokens-full',
  LSP_SELECTION_RANGES: 'async:lsp:selection-ranges',
  LSP_SIGNATURE_HELP: 'async:lsp:signature-help',
  LSP_DOCUMENT_SYMBOLS: 'async:lsp:document-symbols',
  LSP_REFERENCES: 'async:lsp:references',
  LSP_PREPARE_CALL_HIERARCHY: 'async:lsp:prepare-call-hierarchy',
  LSP_CALL_HIERARCHY_INCOMING: 'async:lsp:call-hierarchy-incoming',
  LSP_CALL_HIERARCHY_OUTGOING: 'async:lsp:call-hierarchy-outgoing',
  LSP_WORKSPACE_SYMBOLS: 'async:lsp:workspace-symbols',
  LSP_PREPARE_RENAME: 'async:lsp:prepare-rename',
  LSP_RENAME: 'async:lsp:rename',
  LSP_OUTLINE: 'async:lsp:outline',
  LSP_MODULE_HIERARCHY: 'async:lsp:module-hierarchy',
  LSP_SCHEMATIC: 'async:lsp:schematic',
  LSP_WAVEFORM_OPEN: 'async:lsp:waveform-open',
  LSP_WAVEFORM_FRAME: 'async:lsp:waveform-frame',
  LSP_WAVEFORM_CLOSE: 'async:lsp:waveform-close',
  LSP_LAYOUT_OPEN: 'async:lsp:layout-open',
  LSP_LAYOUT_GEOMETRY: 'async:lsp:layout-geometry',
  LSP_LAYOUT_STATUS: 'async:lsp:layout-status',
  LSP_LAYOUT_CATALOG_SUMMARY: 'async:lsp:layout-catalog-summary',
  LSP_LAYOUT_CATALOG_PAGE: 'async:lsp:layout-catalog-page',
  LSP_LAYOUT_TILE_GEOMETRY: 'async:lsp:layout-tile-geometry',
  LSP_LAYOUT_CLOSE: 'async:lsp:layout-close',
  LSP_GET_DEBUG_EVENTS: 'async:lsp:get-debug-events',
  CONFIG_SET: 'async:config:set',
} as const;

export const StreamChannels = {
  AUTH_STATE_CHANGED: 'stream:auth:state-changed',
  AUTH_ERROR: 'stream:auth:error',
  NOTIFICATIONS_HISTORY_CHANGED: 'stream:notifications:history-changed',
  CONFIG_CHANGED: 'stream:config:changed',
  WORKSPACE_CHANGE: 'stream:workspace:change',
  SHELL_STDOUT: 'stream:shell:stdout',
  SHELL_STDERR: 'stream:shell:stderr',
  SHELL_EXIT: 'stream:shell:exit',
  TERMINAL_DATA: 'stream:terminal:data',
  TERMINAL_EXIT: 'stream:terminal:exit',
  LSP_DEBUG: 'stream:lsp:debug',
  LSP_DIAGNOSTICS: 'stream:lsp:diagnostics',
  LSP_STATE: 'stream:lsp:state',
  MENU_COMMAND: 'stream:menu:command',
  WINDOW_CLOSE_REQUEST: 'stream:window:close-request',
  WINDOW_FOCUS: 'stream:window:focus',
  WINDOW_MAXIMIZED_CHANGE: 'stream:window:maximized-change',
  WINDOW_FULLSCREEN_CHANGE: 'stream:window:full-screen-change',
  PROJECT_CHANGED: 'stream:project:changed',
} as const;
